logging:
  level:
    eu.evropskyrozhled.h2database.service: INFO
    eu.evropskyrozhled.h2database.service.rest: INFO
    org.springframework.web: INFO
    org.hibernate: INFO

server:
  port: 8080
  use-forward-headers: "true"
  shutdown: graceful

spring:
  application:
    name: H2DatabaseService
  lifecycle:
    timeout-per-shutdown-phase: 25s

  datasource:
    url: jdbc:h2:file:~/database/rssreader
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
      enabled: true
  sql:
    init:
      mode: always

management:
  metrics:
    enable:
      all: false
  endpoint:
    metrics:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "metrics"
    jmx:
      exposure:
        exclude: "*"

security:
  internal:
    domain-whitelist: ${REQUEST_DOMAIN_WHITELIST:127.0.0.1,0:0:1}

fixedDelay.in.milliseconds: 3600000
initialDelay.in.milliseconds: 3600000